{% set name = "pyyaml-env-tag" %}
{% set version = "1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyyaml_env_tag-{{ version }}.tar.gz
  sha256: bc952534a872b583f66f916e2dd83e7a7b9087847f4afca6d9c957c48b258ed2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - flit-core
  run:
    - python >={{ python_min }}
    - pyyaml

test:
  imports:
    - yaml_env_tag
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/waylan/pyyaml-env-tag
  summary: A custom YAML tag for referencing environment variables in YAML files.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
