{% set name = "pyyaml-env-tag" %}
{% set version = "0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyyaml_env_tag-{{ version }}.tar.gz
  sha256: 70092675bda14fdec33b31ba77e7543de9ddc88f2e5b99160396572d11525bdb

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - flit-core
  run:
    - python >={{ python_min }}
    - pyyaml

test:
  imports:
    - yaml_env_tag
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/waylan/pyyaml-env-tag
  summary: A custom YAML tag for referencing environment variables in YAML files.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
